/**
 * Leaves Text Effect
 */

const mumaker = require('mumaker');

module.exports = {
    pattern: "leaves",
    alias: [],
    desc: "Create leaves text effect",
    category: "textmaker",
    react: "🍃",
    filename: __filename,
    use: ".leaves <text>",
    
    execute: async (conn, message, m, { from, isGroup, reply }) => {
        try {
            const args = m.args || [];
            const text = args.join(' ');
            
            if (!text) {
                return await reply('Please provide text to generate\nExample: .leaves Nick');
            }
            
            const result = await mumaker.ephoto('https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html', text);
            
            if (!result || !result.image) {
                throw new Error('No image URL received from the API');
            }
            
            const botName = process.env.BOT_NAME || 'ELEPHANT-MD';
            await conn.sendMessage(from, {
                image: { url: result.image },
                caption: `GENERATED BY ${botName}`
            }, { quoted: message });
            
            if (module.exports.react) {
                await conn.sendMessage(from, { react: { text: module.exports.react, key: message.key } });
            }
        } catch (error) {
            console.error('[leaves] error:', error);
            await reply(`Error: ${error.message}`);
        }
    }
};